services:
  sql_injection:
    container_name: sql-injection
    build: .
    ports:
      - "5000:5000"
    restart: unless-stopped
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - ctf_network

networks:
  ctf_network:
    driver: bridge
